### ISSUE TITLE
请问听说过实际项目用中文编写前端代码的吗?

### ISSUE THREAD

**Issue by nobodxbodon** [xinyu198736/hancode#2]
之前做了一点业余尝试: https://zhuanlan.zhihu.com/p/27537616
很想知道有没有实际应用的, 或者业余项目也好.

**Comment by small-tou** [comment]
木有，只是搞着玩

**Comment by nobodxbodon** [comment]
尝试在主流语言里作中文编程的推广. 包括写中文API的库, 和中文代码示例的入门教程, 比如Java的: https://github.com/nobodxbodon/java_in_hours_chn

刚开始着手写JS的类似教程: https://github.com/nobodxbodon/javascript-in-a-day-chn
如果有空请多提意见. 谢谢.

**Comment by small-tou** [comment]
我感觉意义不大。。
